In [8]:
import pandas as pd

In [9]:
df = pd.read_csv('Titanic-Dataset.csv')

In [10]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [11]:
import numpy as np
import matplotlib.pyplot as plt

import seaborn as sns

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [13]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [14]:
df = df.drop('Cabin',axis=1)

In [16]:
from sklearn.impute import  SimpleImputer

print(f"Number of null values in the Age:{df.Age.isnull().sum()}")


s1 =SimpleImputer(strategy = 'mean')


df['Age'] = s1.fit_transform(df[['Age']])
print(f"Number of null values in the Age:{df.Age.isnull().sum()}")

Number of null values in the Age:0
Number of null values in the Age:0

In [17]:
df['Survived'] = s1.fit_transform(df[['Survived']])

In [21]:
s2 = SimpleImputer(strategy='most_frequent')


s2 = SimpleImputer(strategy='most_frequent')

df['Embarked'] = s2.fit_transform(df[['Embarked']]).ravel()

In [22]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [23]:
df = df.drop(['Name','Ticket'],axis=1)

In [24]:
df

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,1,0.0,3,male,22.000000,1,0,7.2500,S
1,2,1.0,1,female,38.000000,1,0,71.2833,C
2,3,1.0,3,female,26.000000,0,0,7.9250,S
3,4,1.0,1,female,35.000000,1,0,53.1000,S
4,5,0.0,3,male,35.000000,0,0,8.0500,S
...,...,...,...,...,...,...,...,...,...
886,887,0.0,2,male,27.000000,0,0,13.0000,S
887,888,1.0,1,female,19.000000,0,0,30.0000,S
888,889,0.0,3,female,29.699118,1,2,23.4500,S
889,890,1.0,1,male,26.000000,0,0,30.0000,C
890,891,0.0,3,male,32.000000,0,0,7.7500,Q

In [29]:
threshold = 3

from scipy.stats import zscore

numerical_features = ['Fare', 'Age']
z_score = np.abs(zscore(df[numerical_features]))

print(z_score)

[[0.85361623 0.90836068]
 [1.87608812 1.08289018]
 [0.84381645 0.41054797]
 ...
 [0.0255643  0.04981898]
 [0.39235618 0.41054797]
 [0.85361623 0.33617111]]

In [30]:
outliers = np.where(z_score > threshold)

print(outliers)

(array([], dtype=int64), array([], dtype=int64))

In [28]:
from scipy.stats.mstats import winsorize

df['Age'] =winsorize(df['Age'],limits=[0.15,0.15])

df["Fare"] = winsorize(df["Fare"], limits=[0.15, 0.15])

In [31]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder()

df['Sex']=oe.fit_transform(df[['Sex']])

In [32]:
df

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,1,0.0,3,1.0,22.000000,1,0,7.7500,S
1,2,1.0,1,0.0,38.000000,1,0,56.4958,C
2,3,1.0,3,0.0,26.000000,0,0,7.9250,S
3,4,1.0,1,0.0,35.000000,1,0,53.1000,S
4,5,0.0,3,1.0,35.000000,0,0,8.0500,S
...,...,...,...,...,...,...,...,...,...
886,887,0.0,2,1.0,27.000000,0,0,13.0000,S
887,888,1.0,1,0.0,19.000000,0,0,30.0000,S
888,889,0.0,3,0.0,29.699118,1,2,23.4500,S
889,890,1.0,1,1.0,26.000000,0,0,30.0000,C
890,891,0.0,3,1.0,32.000000,0,0,7.7500,Q

In [33]:
df["Embarked"] = oe.fit_transform(df[["Embarked"]])

In [34]:
df["Survived"] = oe.fit_transform(df[["Survived"]])

In [35]:
df

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,1,0.0,3,1.0,22.000000,1,0,7.7500,2.0
1,2,1.0,1,0.0,38.000000,1,0,56.4958,0.0
2,3,1.0,3,0.0,26.000000,0,0,7.9250,2.0
3,4,1.0,1,0.0,35.000000,1,0,53.1000,2.0
4,5,0.0,3,1.0,35.000000,0,0,8.0500,2.0
...,...,...,...,...,...,...,...,...,...
886,887,0.0,2,1.0,27.000000,0,0,13.0000,2.0
887,888,1.0,1,0.0,19.000000,0,0,30.0000,2.0
888,889,0.0,3,0.0,29.699118,1,2,23.4500,2.0
889,890,1.0,1,1.0,26.000000,0,0,30.0000,0.0
890,891,0.0,3,1.0,32.000000,0,0,7.7500,1.0

In [36]:
X = df.drop('Survived',axis=1)

y =df['Survived']

In [37]:
from sklearn.model_selection import  train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.30,random_state=0)

In [ ]:
from sklearn.ensemble import AdaBoostClassifier

ab = AdaBoostClassifier(n_estimators = 45,learning_rate=1,random_state=0)

ab.fit(X_train,y_train)

y_pred = ab.predict(X_test)

In [39]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred, y_test)

0.7985074626865671