In [ ]:
import pandas as pd

import numpy as np

import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("smoking.csv")

In [ ]:
df

     outcome smoker  age
0      Alive    Yes   23
1      Alive    Yes   18
2       Dead    Yes   71
3      Alive     No   67
4      Alive     No   64
...      ...    ...  ...
1309   Alive    Yes   35
1310   Alive     No   33
1311   Alive    Yes   21
1312   Alive     No   46
1313   Alive    Yes   41

[1314 rows x 3 columns]

In [4]:
df.head()

  outcome smoker  age
0   Alive    Yes   23
1   Alive    Yes   18
2    Dead    Yes   71
3   Alive     No   67
4   Alive     No   64